import sys
import ply.lex as lex
import ply.yacc as yacc
from semantics import *
from parser import *
from lexer import *
lexer = lex.lex() 

   

def test(input_string):
    lexer.input(input_string)
    print("Tokens generated by lexer:")
    print (list(lexer))
    parser = yacc.yacc() 
    parse_tree = parser.parse(input_string) 
    print ('Successfully built parse tree:')
    print (parse_tree)
    print(parse_tree.semanticAll())
        #debug
    #print ("Your quads: " + str(quadruples))
    for i in range (0, len(quadruples), 1):
        print (str(i) + str(quadruples[i]))
    print("Global: " + str(globalTable.items()))
    print("Local: " + str(localTable.items()))
    print("Aux: " + str(auxTable.items()))

    jsonQuads = "["
    iQuad = 0
    for quad in quadruples:
        jsonQuads += "{\"arg1\":\"" + str(quad[0]) + "\" , \"arg2\":\"" + str(quad[1]) + "\" , \"arg3\":\"" + str(quad[2]) + "\" , \"arg4\":\"" + str(quad[3]) + "\"}"
        if iQuad < len(quadruples)-1:
            jsonQuads += ","
            iQuad += 1
    jsonQuads += "]"
    print (jsonQuads)
    #if isinstance(parse_tree, FuncNode):
#        print (parse_tree.semanticAll())
        # print (memory[0])
        # print (virtual_machine(cuadruplos, memory[0]))
#    else:
#        print ('Failed program')
if len(sys.argv) < 2:
    while True:
        try:
            s = input('code> ')
        except EOFError:
            break
        if not s: continue
        test(s)
else:
    i = 0
    s = ""
    for arg in sys.argv:
        if i == 1:
            s = str(arg)
        i += 1

    test(s)
